services:

  auth:
    build: auth/app
    env_file:
      - ./.env
    restart: unless-stopped
    healthcheck:
      test: bash -c "exec 6<> /dev/tcp/localhost/8000"
      interval: 5s
      timeout: 3s
      retries: 20
    depends_on:
      db:
        condition: service_healthy
        restart: true
      redis:
        condition: service_healthy
        restart: true
      auth_migrate:
        condition: service_completed_successfully
    ports: []

  auth_migrate:
    build: auth/app
    command: alembic upgrade head
    restart: on-failure
    env_file:
      - ./.env
    # restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
        restart: true
