services:

  ugs:
    build: ugs/app
    env_file:
      - ./.env
    restart: unless-stopped
    healthcheck:
      test: bash -c "exec 6<> /dev/tcp/localhost/8000"
      interval: 5s
      timeout: 3s
      retries: 20
    # depends_on:
    #   db:
    #     condition: service_healthy
    #     restart: true
    #   redis:
    #     condition: service_healthy
    #     restart: true
    ports: []
